apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reservations
  name: reservations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservations
  template:
    metadata:
      labels:
        app: reservations
    spec:
      containers:
        # - image: asia-south1-docker.pkg.dev/biggle-ai/reservations/production # GCP Image address
        - image: 555812340215.dkr.ecr.us-east-1.amazonaws.com/reservations:latest # AWS Image address
          name: reservations
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: connectionString
            - name: PORT
              value: '3004'
            - name: AUTH_HOST
              value: auth-tcp
            - name: AUTH_PORT
              value: '3002' # we need to set the tcp port for auth service here since we communicate over that
            - name: PAYMENTS_HOST
              value: payments
            - name: PAYMENTS_PORT
              value: '3001'
          ports:
            - containerPort: 3004
